try :
    x = 45/0
except  Exception as e:
    print('This is cannot be process since', e)
